#if !canImport(ObjectiveC)
import XCTest

extension SQSTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SQSTests = [
        ("testSQSRecordInit", testSQSRecordInit),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(SQSTests.__allTests__SQSTests),
    ]
}
#endif
