#if !canImport(ObjectiveC)
import XCTest

extension S3RecordTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__S3RecordTests = [
        ("testInitCreate", testInitCreate),
        ("testInitDelete", testInitDelete),
    ]
}

extension SNSTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SNSTests = [
        ("testSNSRecordInit", testSNSRecordInit),
    ]
}

extension SQSTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SQSTests = [
        ("testSQSRecordInit", testSQSRecordInit),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(S3RecordTests.__allTests__S3RecordTests),
        testCase(SNSTests.__allTests__SNSTests),
        testCase(SQSTests.__allTests__SQSTests),
    ]
}
#endif
