#!/bin/sh
 
export SSL_CERT_DIR=/etc/pki/tls/certs
export SSL_CERT_FILE=/etc/pki/tls/cert.pem

mkdir -p /etc
cp -R /opt/swift-shared-libs/ssl /etc/ssl

/opt/swift-shared-libs/ld-linux-x86-64.so.2 --library-path /opt/swift-shared-libs/lib $LAMBDA_TASK_ROOT/swiftApp
